# Generated by Django 4.0.4 on 2022-05-06 11:33

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
