# Generated by Django 4.0.4 on 2022-05-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
